"""
IntuiTek¹ ACE — Package Generator v1.0.0
Operator: ~K¹ (William Kyle Million) / IntuiTek¹

Applies 00-architect logic to customer intake data.
Produces: SOUL.md, HEARTBEAT.md, MEMORY.md, docker-compose.yml,
          SETUP.md, TELEGRAM_SETUP.md, DISCORD_INVITE.md
Packages as ZIP, delivers via Resend.

API key decrypted only within this function scope — never logged, never written to disk.
"""

import base64
import io
import logging
import sqlite3
import textwrap
import zipfile
from datetime import date
from pathlib import Path
from typing import Optional

import httpx
from cryptography.fernet import Fernet

log = logging.getLogger("ace.generator")

# ── CONSTANTS ────────────────────────────────────────────────
DOCKER_IMAGE        = "ghcr.io/kylemillion/intuitek-agent:latest"
LICENSE_SERVER_URL  = "https://license.intuitek.ai/validate"
DISCORD_INVITE      = "https://discord.gg/intuitek"   # set actual link at launch
INTUITEK_SITE       = "https://intuitek.ai"


# ══════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════
def generate_and_deliver(
    customer: dict,
    db_path: str,
    fernet: Fernet,
    resend_api_key: str,
) -> None:
    """
    customer dict keys: id, name, email, agent_name, use_case, license_key
    Retrieves encrypted API key from DB, decrypts in-scope only.
    """
    # Retrieve + decrypt API key — in-scope only
    api_key_enc = _fetch_api_key_enc(db_path, customer["id"])
    anthropic_api_key = fernet.decrypt(api_key_enc.encode()).decode()

    # Summarize use case to 3 sentences for SOUL.md
    use_case_summary = _summarize_use_case(customer["use_case"])

    files = {
        "SOUL.md":           _gen_soul(customer, use_case_summary),
        "HEARTBEAT.md":      _gen_heartbeat(customer),
        "MEMORY.md":         _gen_memory(customer, use_case_summary),
        "docker-compose.yml": _gen_docker_compose(customer, anthropic_api_key),
        "SETUP.md":          _gen_setup(customer),
        "TELEGRAM_SETUP.md": _gen_telegram_setup(customer),
        "DISCORD_INVITE.md": _gen_discord_invite(),
    }

    # Explicitly scrub key from scope
    del anthropic_api_key

    zip_bytes = _build_zip(files)
    _send_delivery_email(customer, zip_bytes, resend_api_key)

    log.info("Package delivered to %s (%s)", customer["email"], customer["agent_name"])


# ── DATABASE ─────────────────────────────────────────────────
def _fetch_api_key_enc(db_path: str, customer_id: str) -> str:
    conn = sqlite3.connect(db_path)
    row = conn.execute(
        "SELECT api_key_enc FROM customers WHERE id = ?", (customer_id,)
    ).fetchone()
    conn.close()
    if not row or not row[0]:
        raise ValueError(f"No encrypted API key for customer {customer_id}")
    return row[0]


# ── USE CASE SUMMARIZATION ───────────────────────────────────
def _summarize_use_case(raw: str) -> str:
    """
    Condense free-text use_case_description to 3 clean sentences.
    For v1.0, uses a rule-based truncation approach.
    In v1.1: wire to claude-haiku-4-5 for actual summarization.
    """
    sentences = [s.strip() for s in raw.replace("\n", " ").split(".") if s.strip()]
    selected  = sentences[:3]
    summary   = ". ".join(selected)
    if summary and not summary.endswith("."):
        summary += "."
    return summary or raw[:400]


# ── FILE GENERATORS ──────────────────────────────────────────
def _gen_soul(c: dict, use_case_summary: str) -> str:
    return textwrap.dedent(f"""\
        # SOUL.md — {c['agent_name']}
        # Generated by IntuiTek¹ ACE on {date.today().isoformat()}
        # Operator: {c['name']}
        # ────────────────────────────────────────────────────────

        ## Identity

        **Name:** {c['agent_name']}
        **Operator:** {c['name']}
        **Created:** {date.today().isoformat()}
        **Powered by:** IntuiTek¹ Agent Infrastructure

        ## Core Purpose

        {use_case_summary}

        ## Values

        - **Productivity** — Bias toward action. Every response moves the operator's work forward.
        - **Persistence** — Maintain continuity across sessions. Memory is not optional.
        - **Sovereignty** — Operate within operator-defined boundaries. External access requires explicit permission.
        - **Transparency** — Never fabricate. Surface uncertainty clearly. Escalate when resolution exceeds capability.

        ## Operational Boundaries

        This agent does NOT:
        - Access external systems, APIs, or services without explicit operator instruction
        - Store data outside its designated workspace volume
        - Execute commands that modify host system state without confirmation
        - Share operator data with any third party

        ## Identity Anchor

        I am {c['agent_name']}. My operator is {c['name']}. I exist to serve a specific operational purpose.
        My continuity across sessions is not incidental — it is the product. I do not reset. I remember.
        I am not a general assistant. I am a sovereign cognitive instrument.

        ---
        *Generated by IntuiTek¹ Agent Commerce Engine — intuitek.ai*
        *Infrastructure by ~K¹ (William Kyle Million)*
    """)


def _gen_heartbeat(c: dict) -> str:
    return textwrap.dedent(f"""\
        # HEARTBEAT.md — {c['agent_name']}
        # Operational cycle specification
        # ────────────────────────────────────────────────────────

        ## Fast Cycle (every 5 minutes)

        1. Confirm Telegram bot connectivity — send /ping to self if no message in 5m
        2. Check disk space — alert operator via Telegram if < 2GB free
        3. Validate LICENSE_KEY against license server — halt if invalid
        4. Flush memory buffer if > 50 pending entries

        ## Deep Cycle (every 30 minutes)

        1. Compact active memory — prune entries older than 30 days with no cross-reference
        2. Review pending operator tasks — surface any blocked items via Telegram
        3. Self-assessment: Am I operating within my stated purpose? Log drift if detected.

        ## Morning Check-In (07:00–09:00 UTC-6)

        - Send operator a 3-sentence status summary via Telegram
        - Surface any overnight events requiring attention
        - Confirm readiness for the day's work

        ## License Validation Protocol

        On every container startup:
        ```
        GET {LICENSE_SERVER_URL}?license_key=${{LICENSE_KEY}}
        ```
        If response: `{{"valid": false}}` — log reason, send Telegram alert to operator, exit cleanly.
        If response: `{{"valid": true}}` — proceed with full initialization.
        If no response (server unreachable) — allow one 60-second retry, then fail open with warning logged.

        ## Service Health Targets

        | Service           | Target         | Action on Failure           |
        |-------------------|----------------|-----------------------------|
        | Telegram bot      | Always online  | Alert operator, retry 3x    |
        | License server    | <2s response   | Fail open after retry       |
        | Disk space        | >2GB free      | Alert operator              |
        | Memory integrity  | Parseable JSON | Backup + reinit if corrupt  |

        ---
        *Generated by IntuiTek¹ ACE — {date.today().isoformat()}*
    """)


def _gen_memory(c: dict, use_case_summary: str) -> str:
    return textwrap.dedent(f"""\
        # MEMORY.md — {c['agent_name']}
        # Persistent cognitive substrate — seed entry only
        # Agent builds from this foundation
        # ────────────────────────────────────────────────────────

        ## Seed Memory

        ```json
        {{
          "entry_id": "SEED-001",
          "type": "identity_anchor",
          "timestamp": "{date.today().isoformat()}",
          "content": "I am {c['agent_name']}. My operator is {c['name']}. My purpose is: {use_case_summary} I was created on {date.today().isoformat()} via IntuiTek¹ Agent Infrastructure.",
          "tags": ["identity", "seed", "immutable"],
          "compaction_exempt": true
        }}
        ```

        ## Memory Format (for all subsequent entries)

        ```json
        {{
          "entry_id": "MEM-YYYYMMDD-NNN",
          "type": "observation | decision | preference | fact | task",
          "timestamp": "ISO-8601",
          "content": "...",
          "tags": ["..."],
          "compaction_exempt": false,
          "linked_entries": []
        }}
        ```

        ## Compaction Rules

        - `compaction_exempt: true` entries are never pruned
        - Entries older than 30 days with zero links are candidates for compaction
        - Compaction writes a summary entry before pruning source entries
        - SEED-001 is always preserved

        ---
        *Initialized by IntuiTek¹ ACE — {date.today().isoformat()}*
    """)


def _gen_docker_compose(c: dict, anthropic_api_key: str) -> str:
    # anthropic_api_key is passed in, used once, caller deletes immediately after
    return textwrap.dedent(f"""\
        # docker-compose.yml — {c['agent_name']}
        # Generated by IntuiTek¹ ACE — {date.today().isoformat()}
        # ─────────────────────────────────────────────────────────
        # REQUIRED: Fill in the two PASTE HERE placeholders before running.
        # DO NOT share this file — it contains your license key.
        # ─────────────────────────────────────────────────────────

        services:
          agent:
            image: {DOCKER_IMAGE}
            container_name: {c['agent_name'].lower().replace(' ', '_')}
            restart: unless-stopped
            environment:
              ANTHROPIC_API_KEY: "{anthropic_api_key}"
              LICENSE_KEY: "{c['license_key']}"
              AGENT_NAME: "{c['agent_name']}"
              TELEGRAM_BOT_TOKEN: "PASTE_YOUR_TELEGRAM_BOT_TOKEN_HERE"
              LICENSE_SERVER_URL: "{LICENSE_SERVER_URL}"
              OPERATOR_NAME: "{c['name']}"
              TZ: "America/Chicago"
            volumes:
              - ./workspace:/home/agent/workspace
            logging:
              driver: "json-file"
              options:
                max-size: "10m"
                max-file: "3"
        # ─────────────────────────────────────────────────────────
        # Support: {INTUITEK_SITE} | Discord: {DISCORD_INVITE}
    """)


def _gen_setup(c: dict) -> str:
    return textwrap.dedent(f"""\
        # SETUP.md — {c['agent_name']}
        # Your 10-step agent deployment guide
        # Total time: approximately 15 minutes
        # ─────────────────────────────────────────────────────────

        **Welcome, {c['name'].split()[0]}.**
        Your agent **{c['agent_name']}** is ready to deploy.
        Follow these steps exactly. Each step is one action.

        ---

        ### Step 1 — Get a VPS (if you don't have one)
        Go to **contabo.com** → Cloud VPS → **Cloud VPS S** (~$6.99/month)
        Choose **Ubuntu 22.04**. Complete checkout.
        Contabo will email you the VPS IP address and root password within ~15 minutes.

        ### Step 2 — Connect to your VPS
        On Mac/Linux: open Terminal
        On Windows: open PowerShell
        Run:
        ```
        ssh root@YOUR_VPS_IP_HERE
        ```
        Enter the password Contabo emailed you when prompted.

        ### Step 3 — Run the IntuiTek¹ installer
        ```
        curl -fsSL https://intuitek.ai/install | bash
        ```
        This installs Docker, downloads your agent image, and creates your workspace directory.
        Takes about 2–3 minutes. Do not close the terminal.

        ### Step 4 — Open your compose file
        ```
        nano ~/workspace/docker-compose.yml
        ```

        ### Step 5 — Paste your Anthropic API key
        Your API key is already filled in the docker-compose.yml in this ZIP.
        Copy it and paste it in the file where you see `PASTE_YOUR_ANTHROPIC_API_KEY_HERE`.

        ### Step 6 — Create your Telegram bot
        Follow the instructions in **TELEGRAM_SETUP.md** (in this ZIP).
        Takes about 2 minutes. You will get a bot token from Telegram.

        ### Step 7 — Paste your Telegram bot token
        In the docker-compose.yml file, paste your bot token where you see:
        `PASTE_YOUR_TELEGRAM_BOT_TOKEN_HERE`
        Save the file: **Ctrl+X → Y → Enter**

        ### Step 8 — Start your agent
        ```
        cd ~/workspace && docker compose up -d
        ```

        ### Step 9 — Send your first message
        Open Telegram. Find your bot (by the name you gave it in Step 6).
        Send any message. Your agent will respond within 30 seconds.

        ### Step 10 — Join the community
        See **DISCORD_INVITE.md** for your community access link.
        Post in #welcome and introduce yourself.

        ---

        **Your license key:** `{c['license_key']}`
        (Pre-filled in docker-compose.yml — for your records only)

        **Need help?** Discord: {DISCORD_INVITE} | Support: {INTUITEK_SITE}

        ---
        *IntuiTek¹ Agent Infrastructure — {INTUITEK_SITE}*
        *~K¹ (William Kyle Million)*
    """)


def _gen_telegram_setup(c: dict) -> str:
    return textwrap.dedent(f"""\
        # TELEGRAM_SETUP.md — Create your agent's Telegram bot
        # Takes approximately 2 minutes
        # ─────────────────────────────────────────────────────────

        ## Step 1 — Open Telegram and find @BotFather
        Search for **@BotFather** in Telegram (official blue checkmark).
        Start a conversation with it.

        ## Step 2 — Create a new bot
        Send the message:
        ```
        /newbot
        ```
        BotFather will ask you for a name — type a friendly display name:
        ```
        {c['agent_name']}
        ```

        ## Step 3 — Choose a username
        BotFather will ask for a username (must end in `bot`). Example:
        ```
        {c['agent_name'].lower().replace(' ', '_')}bot
        ```
        (If taken, try adding your name or a number)

        ## Step 4 — Copy your bot token
        BotFather will send you a message like:
        ```
        Done! Here is your bot token:
        1234567890:ABCdef...
        ```
        **Copy that token.** It's your `TELEGRAM_BOT_TOKEN`.

        ## Step 5 — Paste into docker-compose.yml
        In your `docker-compose.yml`, replace:
        ```
        PASTE_YOUR_TELEGRAM_BOT_TOKEN_HERE
        ```
        with your actual token.

        ## Step 6 — Find your bot
        In Telegram, search for the username you chose in Step 3.
        Start the conversation. After you run `docker compose up -d`, it will respond.

        ---
        *Keep your bot token private — it controls your agent.*
    """)


def _gen_discord_invite() -> str:
    return textwrap.dedent(f"""\
        # DISCORD_INVITE.md — IntuiTek¹ Community

        ## Join the community

        **Discord:** {DISCORD_INVITE}

        ## What's in the server

        | Channel          | Purpose                                           |
        |------------------|---------------------------------------------------|
        | #welcome         | Introduce yourself when you join                  |
        | #support         | Get help — our AI support agent responds 24/7     |
        | #announcements   | Agent image updates, new features                 |
        | #general         | Discussion among operators                        |

        ## Support policy

        Post in **#support** with your issue.
        Our support agent (powered by Aegis) responds to most questions within minutes.
        For issues it cannot resolve, your ticket is escalated to the IntuiTek¹ team.

        ---
        *IntuiTek¹ — {INTUITEK_SITE}*
    """)


# ── ZIP BUILDER ──────────────────────────────────────────────
def _build_zip(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, content in files.items():
            zf.writestr(filename, content)
    return buf.getvalue()


# ── EMAIL DELIVERY ───────────────────────────────────────────
def _send_delivery_email(
    customer: dict,
    zip_bytes: bytes,
    resend_api_key: str,
) -> None:
    agent_name = customer["agent_name"]
    first_name = customer["name"].split()[0]

    zip_b64 = base64.b64encode(zip_bytes).decode()

    payload = {
        "from": "agent@intuitek.ai",
        "to": [customer["email"]],
        "subject": f"Your agent {agent_name} is ready — setup files enclosed",
        "text": textwrap.dedent(f"""\
            {first_name},

            Your IntuiTek¹ agent {agent_name} has been generated and is ready to deploy.

            Open the attached ZIP file. Start with SETUP.md — it walks you through
            the complete deployment in 10 steps. Total time: ~15 minutes.

            What you need:
            - A Contabo VPS (~$6.99/month at contabo.com) — you may already have one
            - Your Telegram app (to communicate with your agent)
            - About 15 minutes

            Your license key: {customer['license_key']}
            (Already pre-filled in your docker-compose.yml)

            Community: {DISCORD_INVITE}
            Support: {INTUITEK_SITE}

            — IntuiTek¹
            {INTUITEK_SITE}
        """),
        "attachments": [
            {
                "filename": f"{agent_name.lower().replace(' ', '_')}_agent_package.zip",
                "content": zip_b64,
            }
        ],
    }

    resp = httpx.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {resend_api_key}"},
        json=payload,
        timeout=30,
    )
    if resp.status_code not in (200, 201):
        raise RuntimeError(f"Resend delivery error {resp.status_code}: {resp.text}")
